### ISSUE TITLE
linux binary release links against glibc

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-influxdb-handler#1]
Problem:
linux release links against glibc.

ldd sensu-influxdb-handler
	linux-vdso.so.1 (0x00007ffdb30d2000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f5dc4eed000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f5dc4b2e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5dc510c000)

Fix:
CGO_ENABLED=0  in linux build environment
tested fix on Fedora workstation resulted in fully static binary. 
Seems go defaults to linking glibc when doing a native build, and disables when cross-compiling.

Impact:
Downloaded  sensu-influxdb-handler_1.2_linux_amd64.tar.gz to inject into the sensu nightly docker build and exeuctable fails to operate as expected until glibc libraries are including in the container image as well.

**Comment by portertech** [comment]
I just ran into this issue.

**Comment by nikkictl** [comment]
@portertech @jspaleta TOTALLY spaced on this. I'll get this done asap!

**Comment by nikkictl** [comment]
New builds will be pushed here shortly: https://github.com/nikkiki/sensu-influxdb-handler/releases/tag/v1.4
