### ISSUE TITLE
Unauthenticated connections are not supported

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-influxdb-handler#23]
## Expected behavior

handler can relay metrics to an InfluxDB instance without requiring changes to InfluxDB configuration

## Current behavior

handler requires username and password to be provided, which in turn requires InfluxDB to be reconfigured with authentication enabled

## Context

I am attempting to use this handler with InfluxDB out of the box -- i.e. without enabling authentication nor creating credentials (username, password).

Per the [InfluxDB documentation](https://docs.influxdata.com/influxdb/v1.7/administration/authentication_and_authorization/), authentication is disabled by default.  

I've found that the username and password are required settings, and haven't been successful in passing empty values for these settings.

**Comment by nikkictl** [comment]
Looks like the Influx client code states username and password are optional too. We should adhere to their default behavior in the absence of those flags.
