### ISSUE TITLE
Feature suggestion: Record event status to InfluxDB

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-influxdb-handler#27]
## Expected behavior

As an operator I can configure an instance of this handler to record event statuses in InfluxDB.

## Context

Sensu records an intentionally limited history of statuses for each event (entity/check pair). As an operator I would like to record these statuses in a long-term data store so I can plot statuses against other measurements.

**Comment by jspaleta** [comment]
just saw another request for this sort of pattern from a user in slack.

**Comment by mylesw42** [comment]
This is very useful. What would be the desired workflow for this feature? 

Add a new flag? Maybe "-check_result_only", and it would then only process the event.check.status field? The associated handler would not need to worry about the "has_metrics" filter.

My own personal preference is to setup the check_name as the measurement, with "entity", and "namespace" as tags, and "status" and possibly "output" as fields.

**Comment by nikkictl** [comment]
Closed by https://github.com/sensu/sensu-influxdb-handler/pull/34.
