### ISSUE TITLE
Release 3.6.0 is broken

### ISSUE THREAD

**Issue by davetayl** [sensu/sensu-influxdb-handler#46]
Bonsai is showing a build error for the latest release

https://bonsai.sensu.io/assets/sensu/sensu-influxdb-handler

This asset has compilation errors
Version 3.6.0: missing GitHub release asset for sensu-influxdb-handler_3.6.0_darwin_386.tar.gz

In production, the asset will not install

**Comment by nixwiz** [comment]
3.6.1 has been released and is functional on Bonsai.
